services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_TATUM_ETHEREUM_MAINNET_API_KEY=${VITE_TATUM_ETHEREUM_MAINNET_API_KEY}
      - VITE_TATUM_ETHEREUM_SEPOLIA_API_KEY=${VITE_TATUM_ETHEREUM_SEPOLIA_API_KEY}
    ports:
      - "8080:80"
    restart: unless-stopped

